### ISSUE TITLE
Notebooks cannot establish WS connection

### ISSUE THREAD

**Issue by akranga** [agilestacks/kubeflow-stacks#5]
This seems to be regression of `nginx` ingress controller component. 

Steps to reproduce
1. Deploy a kubeflow cluster
2. Create a JupyterLab notebook
3. Open "dev-tools" in the browser
4. Create terminal in the notebook
5. In dev-tools see something similar to

```
jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2 WebSocket connection to 'wss://kubeflow.grandiose-adder-424.epam.devops.delivery/notebook/myprofile/mynotebook/terminals/websocket/1' failed: 
```

**Comment by TheRealSpaceShip** [comment]
Fixed with agilestacks/kubeflow-components@eeb4628 
Added annotation `nginx.org/websocket-services` to istio-ingressgateway ingress resource.
Details [here](https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/websocket)
